configresolver: fix a case of panic
Follow up a failure job [1] which is triggered by the following command from [2]:

```
/testwith openshift/ovn-kubernetes/master/4.21-upgrade-from-stable-4.20/e2e-aws-ovn-upgrade-ipsec openshift/origin#30481
```

The job led to:

```txt
INFO[2025-11-12T01:52:32Z] ci-operator version v20251111-bd7f225d5
INFO[2025-11-12T01:52:32Z] Loading configuration from https://config.ci.openshift.org for openshift,openshift/ovn-kubernetes,origin@master,main [4.21-upgrade-from-stable-4.20]
ERRO[2025-11-12T01:53:03Z] Failed to load arguments.                     error=failed to load configuration: failed to make request to configresolver: Get "https://config.ci.openshift.org/mergeConfigsWithInjectedTest?branch=master%2Cmain&injectTest=e2e-aws-ovn-upgrade-ipsec&injectTestFromBranch=master&injectTestFromOrg=openshift&injectTestFromRepo=ovn-kubernetes&injectTestFromVariant=4.21-upgrade-from-stable-4.20&org=openshift%2Copenshift&repo=ovn-kubernetes%2Corigin&variant=4.21-upgrade-from-stable-4.20": GET https://config.ci.openshift.org/mergeConfigsWithInjectedTest?branch=master%2Cmain&injectTest=e2e-aws-ovn-upgrade-ipsec&injectTestFromBranch=master&injectTestFromOrg=openshift&injectTestFromRepo=ovn-kubernetes&injectTestFromVariant=4.21-upgrade-from-stable-4.20&org=openshift%2Copenshift&repo=ovn-kubernetes%2Corigin&variant=4.21-upgrade-from-stable-4.20 giving up after 6 attempt(s)
INFO[2025-11-12T01:53:03Z] Reporting job state 'failed' with reason 'loading_args:loading_config'
```

This pull adds a test case to reproduce it. See the output below without the fix.
The fix is to return an error earlier.

```console
$ go test ./pkg/registry/server/...
  time="2025-11-12T09:23:21-05:00" level=info msg="Loading configuration from http://127.0.0.1:61402 for openshift/hyperkube@master"
  time="2025-11-12T09:23:21-05:00" level=info msg="Loading configuration from http://127.0.0.1:61404 for openshift/hyperkube@master"
  time="2025-11-12T09:23:21-05:00" level=info msg="Loading information from http://127.0.0.1:61406 for cluster profile aws"
  time="2025-11-12T09:23:21-05:00" level=info msg="Loading information from http://127.0.0.1:61408 for cluster profile aws"
  --- FAIL: TestResolveAndMergeConfigsAndInjectTest (0.00s)
      --- FAIL: TestResolveAndMergeConfigsAndInjectTest/invalid_variants (0.00s)
  panic: runtime error: index out of range [1] with length 1 [recovered]
          panic: runtime error: index out of range [1] with length 1

  goroutine 122 [running]:
  testing.tRunner.func1.2({0x102dd1800, 0x14000ca8078})
          /Users/hongkliu/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.7.darwin-arm64/src/testing/testing.go:1734 +0x1ac
  testing.tRunner.func1()
          /Users/hongkliu/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.7.darwin-arm64/src/testing/testing.go:1737 +0x334
  panic({0x102dd1800?, 0x14000ca8078?})
          /Users/hongkliu/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.7.darwin-arm64/src/runtime/panic.go:792 +0x124
  github.com/openshift/ci-tools/pkg/registry/server.MetadataEntriesFromQuery({0x10301f260, 0x14000bba940}, 0x1400063adc0)
          /Users/hongkliu/repo/openshift/ci-tools/pkg/registry/server/server.go:479 +0x6f0
  github.com/openshift/ci-tools/pkg/registry/server.TestResolveAndMergeConfigsAndInjectTest.func1.ResolveAndMergeConfigsAndInjectTest.1({0x10301f260, 0x14000bba940}, 0x1400063adc0)
          /Users/hongkliu/repo/openshift/ci-tools/pkg/registry/server/server.go:228 +0xe4
  net/http.HandlerFunc.ServeHTTP(...)
          /Users/hongkliu/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.7.darwin-arm64/src/net/http/server.go:2294
  github.com/openshift/ci-tools/pkg/registry/server.TestResolveAndMergeConfigsAndInjectTest.func1(0x14000c92700)
          /Users/hongkliu/repo/openshift/ci-tools/pkg/registry/server/server_test.go:41 +0x150
  testing.tRunner(0x14000c92700, 0x14000c94770)
          /Users/hongkliu/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.7.darwin-arm64/src/testing/testing.go:1792 +0xe4
  created by testing.(*T).Run in goroutine 118
          /Users/hongkliu/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.7.darwin-arm64/src/testing/testing.go:1851 +0x374
  FAIL    github.com/openshift/ci-tools/pkg/registry/server       1.100s
  FAIL
```

This pull should return more informative output than the current:

```console
$ curl -s "https://config.ci.openshift.org/mergeConfigsWithInjectedTest?branch=master%2Cmain&injectTest=e2e-aws-ovn-upgrade-ipsec&injectTestFromBranch=master&injectTestFromOrg=openshift&injectTestFromRepo=ovn-kubernetes&injectTestFromVariant=4.21-upgrade-from-stable-4.20&org=openshift%2Copenshift&repo=ovn-kubernetes%2Corigin&variant=4.21-upgrade-from-stable-4.20"
<html><body><h1>502 Bad Gateway</h1>
The server returned an invalid or incomplete response.
</body></html>
```

I think we still need to change the client side. It is likely somewhere here [3].

[1]. https://prow.ci.openshift.org/view/gs/test-platform-results/logs/multi-pr-openshift-ovn-kubernetes-2854-openshift-origin-30481-e2e-aws-ovn-upgrade-ipsec/1988424259755577344

[2]. https://github.com/openshift/ovn-kubernetes/pull/2854#issuecomment-3519525099

[3]. https://github.com/openshift/ci-tools/blob/190ee630ffdd57901f5f9cae65338ad5ab1c3058/cmd/ci-operator/main.go#L2265-L2282