test/e2e: report setup errors using original `T`
The E2E `testing.T` wrapper relies on a separate thread to process its `Error`
and `Fatal` messages, since it cannot call those directly from auxiliary
threads, as per the `testing` API requirements:

https://github.com/openshift/ci-tools/blob/a1166b0b93da6845b7c3a39ba3ea73e8e76a1ef1/pkg/testhelper/accessory.go#L85

However, in setup contexts like this, there is no thread yet (it is started by
the `Run` method), so the error is never seen.

---

Before:

```
=== CONT  TestBuildPodAdmission
    accessory.go:239: `kubernetes server` readiness probe: 404 after 1.507µs
    accessory.go:239: `kubernetes server` readiness probe: 404 after 1.012421675s
    accessory.go:239: `kubernetes server` readiness probe: 404 after 2.012596467s
    accessory.go:239: `kubernetes server` readiness probe: 404 after 3.012143864s
    accessory.go:239: `kubernetes server` readiness probe: 404 after 4.012940121s
    accessory.go:239: `kubernetes server` readiness probe: 404 after 5.012219659s
    accessory.go:239: `kubernetes server` readiness probe: 404 after 5.015205646s
    accessory.go:307: found a never-before-seen port, returning: 32777
    accessory.go:307: found a never-before-seen port, returning: 34143
    consumer.go:67: pod-scaler admission starting on port 32777
[test continues…]
```

After:

```console
=== CONT  TestBuildPodAdmission
    kubernetes.go:95: kubernetes server failed to listen: listen tcp 0.0.0.0:8000: bind: address already in use
--- FAIL: TestBuildPodAdmission (0.00s)
FAIL
FAIL    github.com/openshift/ci-tools/test/e2e/pod-scaler       0.062s
FAIL
make[1]: *** [Makefile:169: e2e] Error 1
make[1]: Leaving directory '/home/bbguimaraes/src/ci-tools'
make: *** [Makefile:194: local-e2e] Error 2
```