Remove unnecessary parameter in integration tests
Being negligent about the parameters prevented us from catching
https://github.com/openshift/ci-tools/pull/321 with the existing
integration tests:

```
$ make install integration-ci-operator > /dev/null
$ git revert --no-commit b129c64d35903697444b2fdc4e2e25b58779d7ce
$ make install integration-ci-operator > /dev/null
ERROR: ci-operator failed.
2019/12/13 15:27:42 Resolved source https://github.com/openshift/ci-tools to master@af8a90a2, merging: #1234 538680df @droslean
2019/12/13 15:27:42 Ran for 0s
error: failed to generate steps from config: step "e2e-aws-upgrade" needs a lease but no lease client provided
make: *** [Makefile:48: integration-ci-operator] Error 1
```