pkg/steps/lease: fail faster if client not present
```
2020/09/10 14:07:47 Running [input:root], [release-inputs], src, [images], bin, [release:latest], e2e
2020/09/10 14:07:47 Ran for 1s
error: some steps failed:
  * step "e2e" failed validation: step needs a lease but no lease client provided
  * a lease client was required but none was provided, add the --lease-... arguments
```