Revert "ci-operator: DRY out the relationships between step links and env"
This reverts commit 1f75a22904a7291ce5f198fde908cc3598370b68.

https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-ocp-4.4-e2e-metal-ipi/1288730687381180416
https://search.ci.openshift.org/?search=is+missing+dependencies&maxAge=168h&context=1&type=build-log&name=&maxMatches=5&maxBytes=20971520&groupBy=job

```
$ git switch --quiet master
$ go install ./cmd/ci-operator/
$ RELEASE_IMAGE_LATEST=registry.svc.ci.openshift.org/ocp/release:4.4.0-0.nightly-2020-07-29-210843 ci-operator --target=e2e-metal-ipi --variant=ocp-4.4 --git-ref openshift/release@master
2020/07/30 10:26:27 unset version 0
2020/07/30 10:26:28 Resolved openshift/release@master to commit d736be070bfba753c3665d9102525cbd20ca99bc
2020/07/30 10:26:28 Loading configuration from http://ci-operator-configresolver-ci.apps.ci.l2s4.p1.openshiftapps.com for openshift/release@master [ocp-4.4]
2020/07/30 10:26:29 Resolved source https://github.com/openshift/release to master@d736be07
2020/07/30 10:26:29 Using explicitly provided pull-spec for release latest (registry.svc.ci.openshift.org/ocp/release:4.4.0-0.nightly-2020-07-29-210843)
2020/07/30 10:26:30 Resolved ocp/4.4:base to sha256:bb23e0d0a1dcdc653fb28ef96caee9f1392ca1bcd3152806c657d4fa4b68d84f
2020/07/30 10:26:30 Resolved openshift-kni/test:dev-scripts to sha256:4ea670103e7f6f393b8f38a993ca50bb218456a3e5f2143ad7914103b80a0e9c
2020/07/30 10:26:30 Resolved ocp/4.5:upi-installer to sha256:4c9600ff564f1074c1a3eaabf01d6a52b2d13445af63cdc05a71ceef7f355d0d
2020/07/30 10:26:30 Resolved ocp/4.5:upi-installer to sha256:4c9600ff564f1074c1a3eaabf01d6a52b2d13445af63cdc05a71ceef7f355d0d
2020/07/30 10:26:30 Resolved ocp/4.5:upi-installer to sha256:4c9600ff564f1074c1a3eaabf01d6a52b2d13445af63cdc05a71ceef7f355d0d
2020/07/30 10:26:30 Using namespace https://console.svc.ci.openshift.org/k8s/cluster/projects/ci-op-2jgkrsch
2020/07/30 10:26:30 step <*steps.leaseStep> is missing dependencies: <&api.internalImageStreamTagLink{name:"release", tag:"initial"}>
2020/07/30 10:26:30 step <*steps.leaseStep> is missing dependencies: <&api.internalImageStreamTagLink{name:"release", tag:"initial"}>
2020/07/30 10:26:30 step <*steps.leaseStep> is missing dependencies: <&api.internalImageStreamTagLink{name:"release", tag:"initial"}>
2020/07/30 10:26:30 Ran for 1s
error: some steps failed:
  * could not print execution order: could not sort nodes: steps are missing dependencies
2020/07/30 10:26:30 could not load result reporting options: failed to read file "": open : no such file or directory
$ git log -n 1 f2c2a288f986ef7cd24129b723dd9dd729b3773f
commit f2c2a288f986ef7cd24129b723dd9dd729b3773f
Merge: 8149bb82 1f75a229
Author: OpenShift Merge Robot <openshift-merge-robot@users.noreply.github.com>
Date:   Mon Jul 27 19:35:16 2020 +0200

    Merge pull request #952 from stevekuznetsov/skuznets/env-links

    ci-operator: DRY out the relationships between step links and env
$ git checkout --quiet f2c2a288f986ef7cd24129b723dd9dd729b3773f^
$ go install ./cmd/ci-operator/
$ RELEASE_IMAGE_LATEST=registry.svc.ci.openshift.org/ocp/release:4.4.0-0.nightly-2020-07-29-210843 ci-operator --target=e2e-metal-ipi --variant=ocp-4.4 --git-ref openshift/release@master
2020/07/30 10:27:03 unset version 0
2020/07/30 10:27:04 Resolved openshift/release@master to commit d736be070bfba753c3665d9102525cbd20ca99bc
2020/07/30 10:27:04 Loading configuration from http://ci-operator-configresolver-ci.apps.ci.l2s4.p1.openshiftapps.com for openshift/release@master [ocp-4.4]
2020/07/30 10:27:06 Resolved source https://github.com/openshift/release to master@d736be07
2020/07/30 10:27:06 Using explicitly provided pull-spec for release latest (registry.svc.ci.openshift.org/ocp/release:4.4.0-0.nightly-2020-07-29-210843)
2020/07/30 10:27:06 Resolved openshift-kni/test:dev-scripts to sha256:4ea670103e7f6f393b8f38a993ca50bb218456a3e5f2143ad7914103b80a0e9c
2020/07/30 10:27:06 Resolved ocp/4.5:upi-installer to sha256:4c9600ff564f1074c1a3eaabf01d6a52b2d13445af63cdc05a71ceef7f355d0d
2020/07/30 10:27:07 Resolved ocp/4.4:base to sha256:bb23e0d0a1dcdc653fb28ef96caee9f1392ca1bcd3152806c657d4fa4b68d84f
2020/07/30 10:27:07 Resolved ocp/4.5:upi-installer to sha256:4c9600ff564f1074c1a3eaabf01d6a52b2d13445af63cdc05a71ceef7f355d0d
2020/07/30 10:27:07 Resolved ocp/4.5:upi-installer to sha256:4c9600ff564f1074c1a3eaabf01d6a52b2d13445af63cdc05a71ceef7f355d0d
2020/07/30 10:27:07 Using namespace https://console.svc.ci.openshift.org/k8s/cluster/projects/ci-op-dljfz5hp
2020/07/30 10:27:07 Running [input:dev-scripts], [release:latest], e2e-metal-ipi
…
$ git switch --quiet master
$ git revert --no-edit f2c2a288^2
$ go install ./cmd/ci-operator/
$ RELEASE_IMAGE_LATEST=registry.svc.ci.openshift.org/ocp/release:4.4.0-0.nightly-2020-07-29-210843 ci-operator --target=e2e-metal-ipi --variant=ocp-4.4 --git-ref openshift/release@master
2020/07/30 10:35:18 unset version 0
2020/07/30 10:35:19 Resolved openshift/release@master to commit d736be070bfba753c3665d9102525cbd20ca99bc
2020/07/30 10:35:19 Loading configuration from http://ci-operator-configresolver-ci.apps.ci.l2s4.p1.openshiftapps.com for openshift/release@master [ocp-4.4]
2020/07/30 10:35:20 Resolved source https://github.com/openshift/release to master@d736be07
2020/07/30 10:35:20 Using explicitly provided pull-spec for release latest (registry.svc.ci.openshift.org/ocp/release:4.4.0-0.nightly-2020-07-29-210843)
2020/07/30 10:35:21 Resolved ocp/4.4:base to sha256:bb23e0d0a1dcdc653fb28ef96caee9f1392ca1bcd3152806c657d4fa4b68d84f
2020/07/30 10:35:21 Resolved openshift-kni/test:dev-scripts to sha256:4ea670103e7f6f393b8f38a993ca50bb218456a3e5f2143ad7914103b80a0e9c
2020/07/30 10:35:21 Resolved ocp/4.5:upi-installer to sha256:4c9600ff564f1074c1a3eaabf01d6a52b2d13445af63cdc05a71ceef7f355d0d
2020/07/30 10:35:21 Resolved ocp/4.5:upi-installer to sha256:4c9600ff564f1074c1a3eaabf01d6a52b2d13445af63cdc05a71ceef7f355d0d
2020/07/30 10:35:21 Resolved ocp/4.5:upi-installer to sha256:4c9600ff564f1074c1a3eaabf01d6a52b2d13445af63cdc05a71ceef7f355d0d
2020/07/30 10:35:21 Using namespace https://console.svc.ci.openshift.org/k8s/cluster/projects/ci-op-t0tmpw8s
2020/07/30 10:35:21 Running [input:dev-scripts], [release:latest], e2e-metal-ipi
…
```