private-org-sync: remove duplicate test output
`t.Run` already includes the description in the error output:

```
--- FAIL: TestMirror (0.02s)
    --- FAIL: TestMirror/warm_cache,_destination_needs_to_merge_with_source_->_retries_exceeded,_then_perform_merge_after_fetching_--unshallow,_merge_fails_and_performs_merge_--abort (0.00s)
        main_test.go:225: warm cache, destination needs to merge with source -> retries exceeded, then perform merge after fetching --unshallow, merge fails and performs merge --abort:
            unexpected git call: merge --abort
```

vs.

```
--- FAIL: TestMirror (0.02s)
    --- FAIL: TestMirror/warm_cache,_destination_needs_to_merge_with_source_->_retries_exceeded,_then_perform_merge_after_fetching_--unshallow,_merge_fails_and_performs_merge_--abort (0.00s)
        main_test.go:224: unexpected git call: merge --abort
```